// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "뭐해먹지 - 유튜브 레시피 검색",
  description:
    "집에 있는 식재료로 만들 수 있는 유튜브 레시피 영상을 추천해주는 앱. 즐겨찾기, 유통기한/장보기 리스트까지 한 번에.",
  metadataBase: new URL("https://example.com"), // 나중에 도메인 생기면 바꾸기
  openGraph: {
    title: "뭐해먹지 - 유튜브 레시피 검색",
    description:
      "집에 있는 식재료로 만들 수 있는 유튜브 레시피 영상을 추천해주는 앱",
    type: "website",
  },
  robots: { index: true, follow: true },
  other: {
    "naver-site-verification": "3778420dc15666259655d2eba632415c9ae4da5c",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };
// export const metadata = {
//   title: "뭐해먹지 - 유튜브 레시피 검색",
//   description: "집에 있는 재료로 유튜브 레시피를 바로 찾아주는 앱",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


